<a href="https://colab.research.google.com/github/Heechan-Kim-2869/OSS_11/blob/main/%EC%9E%90%EC%82%B4%EB%A5%A0_%EA%B5%AC%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task
파일 분석해줘

Here is all the data you need:
"Death_rates_for_suicide__by_sex__race__Hispanic_origin__and_age__United_States.csv"

## Data loading

### Subtask:
Load the provided CSV file into a Pandas DataFrame.

**Reasoning**:
Load the provided CSV file into a pandas DataFrame.

In [1]:
import pandas as pd

df = pd.read_csv('Death_rates_for_suicide__by_sex__race__Hispanic_origin__and_age__United_States.csv')
display(df.head())

,INDICATOR,UNIT,UNIT_NUM,STUB_NAME,STUB_NAME_NUM,STUB_LABEL,STUB_LABEL_NUM,YEAR,YEAR_NUM,AGE,AGE_NUM,ESTIMATE,FLAG
0,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1950,1,All ages,0.0,13.2,NaN
1,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1960,2,All ages,0.0,12.5,NaN
2,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1970,3,All ages,0.0,13.1,NaN
3,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1980,4,All ages,0.0,12.2,NaN
4,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1981,5,All ages,0.0,12.3,NaN

## Data exploration

### Subtask:
Explore the loaded data to understand its structure and key characteristics.

**Reasoning**:
Examine the DataFrame's shape, data types, and unique values in specified columns to understand its structure and key characteristics.

In [2]:
# Determine the shape of the DataFrame.
print(f"Shape of the DataFrame: {df.shape}")

# Identify the data type of each column.
print("\nData types of each column:")
print(df.dtypes)

# Identify unique values and their counts for specified columns.
for col in ['Sex', 'Race', 'Hispanic Origin', 'Age Group']:
    if col in df.columns:
        print(f"\nUnique values and counts for '{col}':")
        try:
            print(df[col].value_counts())
        except TypeError:
            print(f"Column '{col}' has a non-categorical data type and cannot be used with value_counts().")
    else:
        print(f"\nColumn '{col}' not found in the DataFrame.")

Shape of the DataFrame: (6390, 13)

Data types of each column:
INDICATOR          object
UNIT               object
UNIT_NUM            int64
STUB_NAME          object
STUB_NAME_NUM       int64
STUB_LABEL         object
STUB_LABEL_NUM    float64
YEAR                int64
YEAR_NUM            int64
AGE                object
AGE_NUM           float64
ESTIMATE          float64
FLAG               object
dtype: object

Column 'Sex' not found in the DataFrame.

Column 'Race' not found in the DataFrame.

Column 'Hispanic Origin' not found in the DataFrame.

Column 'Age Group' not found in the DataFrame.

## Data analysis

### Subtask:
Calculate descriptive statistics for the 'Death Rate' column, grouped by relevant columns.

**Reasoning**:
Calculate descriptive statistics for the 'ESTIMATE' column, grouped by 'YEAR' and 'AGE'.

In [3]:
import pandas as pd

# Calculate overall descriptive statistics for 'ESTIMATE'.
overall_stats = df['ESTIMATE'].describe()
print("Overall Descriptive Statistics for 'ESTIMATE':\n", overall_stats)

# Group data by 'YEAR' and calculate descriptive statistics.
yearly_stats = df.groupby('YEAR')['ESTIMATE'].describe()
print("\nDescriptive Statistics for 'ESTIMATE' by Year:\n", yearly_stats)

# Group data by 'AGE' and calculate descriptive statistics.
if 'AGE' in df.columns:
    age_stats = df.groupby('AGE')['ESTIMATE'].describe()
    print("\nDescriptive Statistics for 'ESTIMATE' by Age:\n", age_stats)
else:
    print("\nColumn 'AGE' not found in the DataFrame.")

Overall Descriptive Statistics for 'ESTIMATE':
 count    5484.000000
mean       13.709810
std        11.531805
min         0.300000
25%         5.000000
50%        10.500000
75%        19.500000
max        74.800000
Name: ESTIMATE, dtype: float64

Descriptive Statistics for 'ESTIMATE' by Year:
       count       mean        std  min    25%    50%     75%   max
YEAR
1950   74.0  17.017568  16.965310  0.3  5.700   9.90  22.050  61.9
1960   73.0  16.171233  14.883431  0.5  5.900  10.20  21.100  61.3
1970   76.0  15.542105  11.538125  0.3  7.775  12.30  20.800  45.8
1980   93.0  14.989247  11.338655  0.3  6.100  11.80  19.900  52.8
1981   81.0  14.904938  11.163645  0.5  6.300  12.20  20.000  54.0
1982   81.0  15.116049  11.817799  0.4  6.200  12.20  20.500  54.5
1983   80.0  15.571250  12.410849  0.6  6.450  13.15  20.700  57.9
1984   81.0  15.640741  12.437833  0.6  6.200  12.70  21.300  56.3
1985  118.0  15.042373  12.539199  0.9  5.725  12.45  21.075  60.9
1986  104.0  15.898077  13.461726  0.7  5.975  12.90  22.325  66.5
1987  104.0  15.939423  14.032870  0.7  5.800  12.75  21.900  72.1
1988  118.0  15.221186  13.193671  0.8  5.625  12.35  21.275  66.5
1989  118.0  15.343220  13.362158  0.7  5.325  12.35  22.100  72.9
1990  118.0  15.394915  13.544771  0.8  5.325  12.95  22.150  70.3
1991  119.0  15.195798  13.218941  0.7  5.350  12.90  22.100  74.8
1992  120.0  14.381667  12.391709  0.9  5.000  11.90  21.550  67.1
1993  121.0  14.585124  12.575589  0.9  5.100  12.10  21.900  73.2
1994  120.0  14.553333  12.622875  0.9  5.000  12.45  21.325  71.0
1995  120.0  14.195000  11.982171  0.8  4.875  12.10  21.025  67.9
1996  122.0  13.563115  11.571247  0.8  4.800  11.25  19.800  65.5
1997  120.0  13.430833  11.395442  0.8  4.775  11.20  19.325  65.2
1998  121.0  13.164463  11.455747  0.9  4.700  10.70  19.600  64.5
1999  153.0  11.850327  10.303820  0.5  4.100   9.80  16.500  61.5
2000  152.0  11.706579  10.166454  0.6  4.000   9.70  17.100  61.6
2001  152.0  11.809211  10.092777  0.6  3.900   9.20  17.525  56.6
2002  152.0  11.941447  10.304525  0.6  4.100   9.25  16.500  57.8
2003  154.0  11.606494  10.003729  0.5  4.000   8.85  16.000  55.2
2004  153.0  12.204575   9.778550  0.9  4.400   9.60  16.700  52.5
2005  155.0  11.775484   9.979846  0.7  4.100   9.00  16.650  53.1
2006  153.0  11.886275   9.773622  0.6  4.200   9.50  16.500  50.8
2007  152.0  12.061184   9.779415  0.5  4.300   9.05  16.625  50.1
2008  157.0  12.012102   9.786754  0.7  4.500   9.40  16.000  45.8
2009  157.0  12.233121   9.828943  0.9  4.600   9.60  16.400  47.3
2010  155.0  12.807097  10.294811  0.9  4.700   9.80  17.550  51.9
2011  157.0  12.600637  10.143436  0.8  4.800   9.40  16.900  47.0
2012  153.0  13.290850  10.559514  0.8  5.100  10.00  18.000  50.7
2013  155.0  13.249032  10.773768  1.2  5.250   9.70  18.200  52.6
2014  157.0  13.447134  10.622446  1.3  5.300   9.90  18.200  54.4
2015  159.0  13.925786  10.819937  0.9  5.600  10.20  19.150  52.5
2016  158.0  14.350633  11.338260  1.4  5.800  10.60  19.700  57.5
2017  159.0  14.865409  11.646078  1.3  6.100  11.20  20.300  58.1
2018  259.0  15.290347  12.300225  1.3  6.100  11.50  20.150  60.7

Descriptive Statistics for 'ESTIMATE' by Age:
                     count       mean        std  min     25%    50%     75%  \
AGE
10-14 years         124.0   1.420968   0.686724  0.3   0.875   1.40   1.900
15-19 years         126.0   8.648413   4.786009  1.6   3.700   8.55  11.950
15-24 years         674.0  12.193769  10.191580  1.2   4.000  10.50  16.900
20-24 years         126.0  13.757937   8.061805  2.9   5.100  13.70  20.975
25-34 years         126.0  14.323810   7.380389  4.3   6.225  14.65  21.075
25-44 years         695.0  13.647194  10.096181  1.9   5.950  10.80  20.050
35-44 years         126.0  15.565873   6.798531  6.4   7.700  15.20  22.800
45-54 years         126.0  17.075397   7.381314  6.6   9.925  16.25  22.600
45-64 years         657.0  12.704566   8.854781  1.6   6.300  10.20  16.800
55-64 years         126.0  16.578571   8.268568  5.2   8.725  16.00  22.475
65 years and over   566.0  15.073322  12.666919  0.9   5.200  11.40  19.950
65-74 years         212.0  18.478774  10.632195  3.7   8.550  16.25  26.600
75-84 years         209.0  25.565550  17.058183  3.6  11.200  19.90  38.800
85 years and over   169.0  34.504734  23.653540  3.2  16.400  42.40  54.500
All ages           1422.0  10.200352   7.317537  1.4   4.300   8.50  15.325

                    max
AGE
10-14 years         3.7
15-19 years        18.1
15-24 years        60.7
20-24 years        28.0
25-34 years        27.6
25-44 years        60.2
35-44 years        28.1
45-54 years        32.0
45-64 years        39.5
55-64 years        43.6
65 years and over  55.8
65-74 years        53.2
75-84 years        61.9
85 years and over  74.8
All ages           34.8

## Summary:

### 1. Q&A

No questions were explicitly asked in the provided data analysis task.  However, the analysis implicitly addresses questions like:

* What is the overall distribution of suicide death rates?
* How do suicide death rates vary by year?
* How do suicide death rates vary by age group?


### 2. Data Analysis Key Findings

* **Dataframe Shape:** The DataFrame has 6390 rows and 13 columns.
* **Missing Columns:** The columns 'Sex', 'Race', 'Hispanic Origin', and 'Age Group' (as specified in the original request), were not found in the DataFrame.
* **Overall Death Rate:** The average suicide death rate ('ESTIMATE') is approximately 13.71, with a standard deviation of 11.53, a minimum of 0.3 and a maximum of 74.8.
* **Death Rate Variation by Year:** Suicide death rates fluctuate across different years, suggesting a time-dependent trend.
* **Death Rate Variation by Age:**  Suicide death rates vary significantly across different age groups, with lower rates in younger age groups (e.g., 10-14) and generally increasing rates with age.


### 3. Insights or Next Steps

* **Investigate Temporal Trends:** Further analyze the yearly trends in suicide death rates to identify potential contributing factors and periods of significant change.  This could involve time series analysis or correlation with external factors.
* **Explore Other Variables:**  Since the originally requested columns ('Sex', 'Race', 'Hispanic Origin', and 'Age Group') are not present, locate these variables in the dataset or seek an alternative dataset that includes them to examine how these demographic factors relate to suicide death rates.

In [12]:
# prompt: /content/Death_rates_for_suicide__by_sex__race__Hispanic_origin__and_age__United_States.csv
# 연도를 입력하면 해당 년도의 자살률을 나이대별로 출력하는 코드를 짤거야. 1950~2018 사이의 연도를 입력하게 해줘. 연도를 입력하면 데이터에서 "ESTIMATE" column을 조사해서 해당 연도의 평균을 구해줘. 평균치는 반올림한 정수로 나타내줘. 또한 해당 년도의 데이터 중, 나이를 나타내는 데이터가 있다면 따로 수집해서 나이대별로 10살씩 다시 "ESTIMATE" column을 평균을 구해서 출력해줘. 이 평균치는 소숫점 한 자릿수의 실수로 출력해줘.

import pandas as pd

def analyze_suicide_rates(year):
    df = pd.read_csv('/content/Death_rates_for_suicide__by_sex__race__Hispanic_origin__and_age__United_States.csv')

    if not 1950 <= year <= 2018:
        print("Please enter a year between 1950 and 2018.")
        return

    # Calculate the overall average death rate for the given year
    yearly_data = df[df['YEAR'] == year]
    average_death_rate = round(yearly_data['ESTIMATE'].mean())
    print(f"The average suicide death rate in {year} is: {average_death_rate}")

    # Analyze age-specific death rates
    if 'AGE' in df.columns:  #Check if the 'AGE' column exists
        age_groups = yearly_data['AGE'].unique()
        for age_group in age_groups:
            age_specific_data = yearly_data[yearly_data['AGE'] == age_group]
            avg_rate = age_specific_data["ESTIMATE"].mean()
            print(f"Average death rate for age group {age_group}: {avg_rate:.1f}")
    else:
        print("Age-specific data not available in the dataset.")

# Get user input for the year
year_input = int(input("Enter a year between 1950 and 2018: "))
analyze_suicide_rates(year_input)

Enter a year between 1950 and 2018: 1987
The average suicide death rate in 1987 is: 16
Average death rate for age group All ages: 10.9
Average death rate for age group 10-14 years: 1.5
Average death rate for age group 15-24 years: 11.0
Average death rate for age group 15-19 years: 10.1
Average death rate for age group 20-24 years: 14.9
Average death rate for age group 25-44 years: 13.6
Average death rate for age group 25-34 years: 15.5
Average death rate for age group 35-44 years: 15.1
Average death rate for age group 45-64 years: 13.7
Average death rate for age group 45-54 years: 16.2
Average death rate for age group 55-64 years: 17.2
Average death rate for age group 65 years and over: 22.3
Average death rate for age group 65-74 years: 23.9
Average death rate for age group 75-84 years: 34.3
Average death rate for age group 85 years and over: 41.7

# 해당 년도의 평균 자살률과 나이대별 평균 자살률 구하기

## 데이터 선택
데이터는 미국 정부에서 운영하는 오픈 데이터 사이트를 이용함.

**Death rates for suicide, by sex, race, Hispanic origin, and age: United States**

https://data.gov/

데이터 중, 미국에서 일어난 자살을 성별, 인종, 히스패닉 여부, 나이에 따라 정리된 데이터를 발견하였고, 이 데이터를 이용하여 과제를 수행함.

https://catalog.data.gov/dataset/death-rates-for-suicide-by-sex-race-hispanic-origin-and-age-united-states-020c1

## 데이터 분석

Gemini를 이용하여 데이터에서 어떤 분석을 기대할 수 있을지를 의뢰함. 데이터에서 성별과 인종 등의 나이를 제외한 데이터들은 있는 경우도 있고 없는 경우도 있어, 완벽하게 분석할 수 없다는 사실을 알게됨.

## 코드 만들기

다음은 생성형 AI를 이용해 연도와 나이대에 따른 자살률을 얻기 위해 입력한 값임.

*/content/Death_rates_for_suicide__by_sex__race__Hispanic_origin__and_age__United_States.csv*

*연도를 입력하면 해당 년도의 자살률을 나이대별로 출력하는 코드를 짤거야. 1950~2018 사이의 연도를 입력하게 해줘. 연도를 입력하면 데이터에서 "ESTIMATE" column을 조사해서 해당 연도의 평균을 구해줘. 평균치는 반올림한 정수로 나타내줘. 또한 해당 년도의 데이터 중, 나이를 나타내는 데이터가 있다면 따로 수집해서 나이대별로 10살씩 다시 "ESTIMATE" column을 평균을 구해서 출력해줘. 이 평균치는 소숫점 한 자릿수의 실수로 출력해줘.*

## 코드 실행 후 입력

코드 실행 시 데이터세트의 연도의 범위를 설정하기 위해 이를 생성형 AI에게 주문했으며, 실행 시 *Please enter a year between 1950 and 2018.*이라는 문구가 출력되며 해당하는 연도를 입력하면 됨.

## 코드 결과

코드의 결과는 해당 연도의 자살률과 나이대별의 자살률의 평균값을 구해서 출력하며, 출력 결과는 다음과 같음.


*  예시, '1987'을 입력.

*Enter a year between 1950 and 2018: 1987
The average suicide death rate in 1987 is: 16
Average death rate for age group All ages: 10.9
Average death rate for age group 10-14 years: 1.5
Average death rate for age group 15-24 years: 11.0
Average death rate for age group 15-19 years: 10.1
Average death rate for age group 20-24 years: 14.9
Average death rate for age group 25-44 years: 13.6
Average death rate for age group 25-34 years: 15.5
Average death rate for age group 35-44 years: 15.1
Average death rate for age group 45-64 years: 13.7
Average death rate for age group 45-54 years: 16.2
Average death rate for age group 55-64 years: 17.2
Average death rate for age group 65 years and over: 22.3
Average death rate for age group 65-74 years: 23.9
Average death rate for age group 75-84 years: 34.3
Average death rate for age group 85 years and over: 41.7*

## 결론

코드가 정상적으로 작동하며, 요청한 대로 해당 연도의 자살률은 정수로 나타내며 나이대별 사망률은 소숫점 한자리의 실수로 나타냄.

In [ ]:
# prompt: /content/Death_rates_for_suicide__by_sex__race__Hispanic_origin__and_age__United_States.csv
# 연도를 입력하면 해당 년도의 자살률을 나이대별로 출력하는 코드를 짤거야. 1950~2018 사이의 연도를 입력하게 해줘. 연도를 입력하면 데이터에서 "ESTIMATE" column을 조사해서 해당 연도의 평균을 구해줘. 평균치는 반올림한 정수로 나타내줘. 또한 해당 년도의 데이터 중, 나이를 나타내는 데이터가 있다면 따로 수집해서 나이대별로 10살씩 다시 "ESTIMATE" column을 평균을 구해서 출력해줘. 이 평균치는 소숫점 한 자릿수의 실수로 출력해줘.

import pandas as pd

def analyze_suicide_rates(year):
    df = pd.read_csv('/content/Death_rates_for_suicide__by_sex__race__Hispanic_origin__and_age__United_States.csv')

    if not 1950 <= year <= 2018:
        print("Please enter a year between 1950 and 2018.")
        return

    # Calculate the overall average death rate for the given year
    yearly_data = df[df['YEAR'] == year]
    average_death_rate = round(yearly_data['ESTIMATE'].mean())
    print(f"The average suicide death rate in {year} is: {average_death_rate}")

    # Analyze age-specific death rates
    if 'AGE' in df.columns:  #Check if the 'AGE' column exists
        age_groups = yearly_data['AGE'].unique()
        for age_group in age_groups:
            age_specific_data = yearly_data[yearly_data['AGE'] == age_group]
            avg_rate = age_specific_data["ESTIMATE"].mean()
            print(f"Average death rate for age group {age_group}: {avg_rate:.1f}")
    else:
        print("Age-specific data not available in the dataset.")

# Get user input for the year
year_input = int(input("Enter a year between 1950 and 2018: "))
analyze_suicide_rates(year_input)